// 30-Day Content Calendar - Detailed Progress Tracker
// April 18 - May 18, 2026

export interface CalendarDay {
  day: number;
  date: string;
  dayOfWeek: string;
  week: number;
  theme: string;
  contentType: "REEL" | "CAROUSEL" | "STATIC" | "STORY" | "ENGAGEMENT";
  title: string;
  description: string;
  objectives: string[];
  contentIdeas: string[];
  hashtags: string[];
  estimatedTime: string;
  expectedReach: string;
  pointsValue: number;
  completed: boolean;
  notes: string;
}

export const detailedCalendar: CalendarDay[] = [
  // WEEK 1: Foundation & Onboarding (April 18-24)
  {
    day: 1,
    date: "April 18, 2026",
    dayOfWeek: "Friday",
    week: 1,
    theme: "GSA Journey Kickoff",
    contentType: "REEL",
    title: "GSA 2026 Journey Begins 🚀",
    description:
      "Launch your GSA ambassador journey with an energetic reel showing your onboarding experience, campus highlights, and commitment to the program.",
    objectives: [
      "Introduce yourself as a GSA ambassador",
      "Showcase enthusiasm and commitment",
      "Establish credibility in AI/tech space",
      "Drive initial engagement from followers",
    ],
    contentIdeas: [
      "Quick clips from GSA onboarding event",
      "Your reaction to becoming an ambassador",
      "Campus tour highlighting tech facilities",
      "Testimonial about why you joined GSA",
      "Behind-the-scenes of GSA materials",
    ],
    hashtags: [
      "#GoogleStudentAmbassador",
      "#GSA2026",
      "#TeamGemini",
      "#AIJourney",
      "#StudentLeader",
    ],
    estimatedTime: "45-60 minutes",
    expectedReach: "800-1200 accounts",
    pointsValue: 100,
    completed: true,
    notes: "Already posted - 56 likes, 7 comments. Great engagement!",
  },
  {
    day: 2,
    date: "April 19, 2026",
    dayOfWeek: "Saturday",
    week: 1,
    theme: "Engagement & Community",
    contentType: "ENGAGEMENT",
    title: "Engage with GSA Community",
    description:
      "Spend 30 minutes engaging with other GSA ambassadors' content. Like, comment, and share insights to build community.",
    objectives: [
      "Build relationships with fellow ambassadors",
      "Increase visibility in GSA network",
      "Learn from peer content",
      "Establish thought leadership",
    ],
    contentIdeas: [
      "Comment on 5-10 GSA posts with meaningful insights",
      "Share a GSA post to your stories with your thoughts",
      "Reply to comments on your posts",
      "DM 2-3 ambassadors to collaborate",
    ],
    hashtags: ["#GSACommunity", "#AmbassadorNetwork"],
    estimatedTime: "30 minutes",
    expectedReach: "Network visibility",
    pointsValue: 25,
    completed: false,
    notes: "Focus on quality engagement, not just likes",
  },
  {
    day: 3,
    date: "April 20, 2026",
    dayOfWeek: "Sunday",
    week: 1,
    theme: "Educational Content",
    contentType: "CAROUSEL",
    title: "5 Must-Have AI Tools for Students",
    description:
      "Create an educational carousel showcasing 5 essential AI tools that students should know about, with practical use cases.",
    objectives: [
      "Provide educational value",
      "Position yourself as AI expert",
      "Drive saves and shares",
      "Build authority in niche",
    ],
    contentIdeas: [
      "Slide 1: Eye-catching title with AI theme",
      "Slides 2-6: One tool per slide with use case",
      "Include screenshots of each tool",
      "Add practical tips for each tool",
      "Final slide: Call-to-action for comments",
    ],
    hashtags: [
      "#AITools",
      "#StudentTech",
      "#ProductivityHacks",
      "#TechForStudents",
      "#GoogleGemini",
    ],
    estimatedTime: "60-90 minutes",
    expectedReach: "1000-1500 accounts",
    pointsValue: 100,
    completed: false,
    notes: "Carousels drive 3x more engagement than static posts",
  },
  {
    day: 4,
    date: "April 21, 2026",
    dayOfWeek: "Monday",
    week: 1,
    theme: "Motivation & Inspiration",
    contentType: "STATIC",
    title: "Your GSA Mindset Quote",
    description:
      "Share an inspiring quote about learning, growth, or technology with a personal reflection on what it means to you.",
    objectives: [
      "Build personal brand",
      "Create shareable content",
      "Inspire your audience",
      "Drive story shares",
    ],
    contentIdeas: [
      "Quote with beautiful background design",
      "Your personal story tied to the quote",
      "Call-to-action: Share your growth story",
      "Include relevant emojis and design elements",
    ],
    hashtags: [
      "#Motivation",
      "#Growth",
      "#StudentLife",
      "#Inspiration",
      "#TechCommunity",
    ],
    estimatedTime: "30-45 minutes",
    expectedReach: "600-900 accounts",
    pointsValue: 50,
    completed: false,
    notes: "Best time to post: 6-9 PM IST on weekdays",
  },
  {
    day: 5,
    date: "April 22, 2026",
    dayOfWeek: "Tuesday",
    week: 1,
    theme: "Behind-the-Scenes",
    contentType: "STORY",
    title: "Day in Life as GSA Ambassador",
    description:
      "Share 5-7 story slides showing a typical day as a GSA ambassador - classes, studying, working on GSA tasks.",
    objectives: [
      "Show authentic daily life",
      "Build personal connection",
      "Increase story views",
      "Drive profile visits",
    ],
    contentIdeas: [
      "Morning routine with tech",
      "Class or study session",
      "Working on GSA content",
      "Lunch/break moment",
      "Evening reflection",
      "Interactive poll or question",
    ],
    hashtags: ["#DayInMyLife", "#AmbassadorLife", "#BehindTheScenes"],
    estimatedTime: "20-30 minutes",
    expectedReach: "Followers + close friends",
    pointsValue: 25,
    completed: false,
    notes: "Stories are great for daily engagement without algorithm pressure",
  },
  {
    day: 6,
    date: "April 23, 2026",
    dayOfWeek: "Wednesday",
    week: 1,
    theme: "Community Engagement",
    contentType: "ENGAGEMENT",
    title: "Host Q&A Session in Stories",
    description:
      "Use Instagram story polls and questions to engage your audience. Ask about their biggest tech challenges or learning goals.",
    objectives: [
      "Increase audience interaction",
      "Gather audience insights",
      "Boost story engagement metrics",
      "Create content ideas from responses",
    ],
    contentIdeas: [
      "Poll: What's your biggest tech challenge?",
      "Question: What AI tool do you want to learn?",
      "Poll: Reel or Carousel preference?",
      "Question: Your learning goal this month?",
      "Share responses in next post",
    ],
    hashtags: ["#AskMe", "#CommunityFirst"],
    estimatedTime: "20 minutes",
    expectedReach: "Story viewers",
    pointsValue: 25,
    completed: false,
    notes: "Interactive content gets 2x more engagement",
  },
  {
    day: 7,
    date: "April 24, 2026",
    dayOfWeek: "Thursday",
    week: 1,
    theme: "Week Recap & Planning",
    contentType: "CAROUSEL",
    title: "Week 1 Recap: What I Learned",
    description:
      "Reflect on Week 1 of your GSA journey. Share 3-5 key learnings, challenges overcome, and goals for Week 2.",
    objectives: [
      "Demonstrate progress and growth",
      "Build narrative arc",
      "Encourage audience reflection",
      "Set up Week 2 momentum",
    ],
    contentIdeas: [
      "Slide 1: Week 1 Recap title",
      "Slides 2-4: Key learnings with visuals",
      "Slide 5: Challenges and solutions",
      "Slide 6: Week 2 goals and commitments",
      "Final slide: Call-to-action",
    ],
    hashtags: [
      "#WeeklyRecap",
      "#GrowthJourney",
      "#GSA2026",
      "#Reflection",
      "#NextWeek",
    ],
    estimatedTime: "60 minutes",
    expectedReach: "1000-1400 accounts",
    pointsValue: 100,
    completed: false,
    notes: "Recap posts perform well on Thursdays/Fridays",
  },

  // WEEK 2: Educational Deep Dive (April 25 - May 1)
  {
    day: 8,
    date: "April 25, 2026",
    dayOfWeek: "Friday",
    week: 2,
    theme: "Google Gemini Spotlight",
    contentType: "REEL",
    title: "Google Gemini Tutorial: Getting Started",
    description:
      "Create a quick tutorial reel showing how to access and use Google Gemini for the first time. Make it beginner-friendly.",
    objectives: [
      "Educate audience on Gemini",
      "Position as Gemini expert",
      "Drive engagement on Gemini content",
      "Fulfill GSA content requirements",
    ],
    contentIdeas: [
      "Screen recording of Gemini interface",
      "Step-by-step walkthrough",
      "Show 3 practical use cases",
      "Tips and tricks",
      "Call-to-action: Try it yourself",
    ],
    hashtags: [
      "#GoogleGemini",
      "#AITutorial",
      "#HowTo",
      "#TechTutorial",
      "#GoogleAI",
    ],
    estimatedTime: "60-90 minutes",
    expectedReach: "1200-1800 accounts",
    pointsValue: 100,
    completed: false,
    notes: "Tutorial reels get high save rates - great for algorithm",
  },
  {
    day: 9,
    date: "April 26, 2026",
    dayOfWeek: "Saturday",
    week: 2,
    theme: "Community Engagement",
    contentType: "ENGAGEMENT",
    title: "Respond to Comments & DMs",
    description:
      "Dedicate time to respond to all comments on recent posts and reply to DMs. Build relationships and show you care about your community.",
    objectives: [
      "Increase comment engagement",
      "Build community loyalty",
      "Boost post performance",
      "Create content from questions",
    ],
    contentIdeas: [
      "Reply to all comments thoughtfully",
      "Answer DM questions in detail",
      "Create a post addressing common questions",
      "Thank people for engagement",
    ],
    hashtags: ["#CommunityFirst"],
    estimatedTime: "30-45 minutes",
    expectedReach: "Direct engagement",
    pointsValue: 25,
    completed: false,
    notes: "Instagram algorithm rewards accounts with high engagement rates",
  },
  {
    day: 10,
    date: "April 27, 2026",
    dayOfWeek: "Sunday",
    week: 2,
    theme: "Student Success Stories",
    contentType: "CAROUSEL",
    title: "Student Success: How AI Changed My Learning",
    description:
      "Share a real or hypothetical success story of a student using AI to improve their learning. Make it relatable and inspiring.",
    objectives: [
      "Inspire your audience",
      "Show practical AI applications",
      "Drive engagement and shares",
      "Build thought leadership",
    ],
    contentIdeas: [
      "Slide 1: Compelling title",
      "Slide 2: The challenge",
      "Slide 3: The AI solution",
      "Slide 4: Results and impact",
      "Slide 5: Key takeaways",
      "Slide 6: Call-to-action",
    ],
    hashtags: [
      "#SuccessStory",
      "#AIInEducation",
      "#StudentSuccess",
      "#Learning",
      "#Transformation",
    ],
    estimatedTime: "60-90 minutes",
    expectedReach: "1000-1500 accounts",
    pointsValue: 100,
    completed: false,
    notes: "Success stories drive high engagement and shares",
  },
  {
    day: 11,
    date: "April 28, 2026",
    dayOfWeek: "Monday",
    week: 2,
    theme: "Motivation & Mindset",
    contentType: "STATIC",
    title: "Monday Motivation: Start Your Week Right",
    description:
      "Share a motivational message or tip to help your audience start their week strong with a focus on learning and growth.",
    objectives: [
      "Build personal brand",
      "Create shareable content",
      "Drive engagement on Mondays",
      "Inspire your audience",
    ],
    contentIdeas: [
      "Motivational quote with design",
      "Personal story or insight",
      "Weekly challenge or goal",
      "Actionable tip for the week",
    ],
    hashtags: [
      "#MondayMotivation",
      "#WeekStart",
      "#Mindset",
      "#Growth",
      "#Inspiration",
    ],
    estimatedTime: "30-45 minutes",
    expectedReach: "700-1000 accounts",
    pointsValue: 50,
    completed: false,
    notes: "Monday posts get high engagement - people are motivated at week start",
  },
  {
    day: 12,
    date: "April 29, 2026",
    dayOfWeek: "Tuesday",
    week: 2,
    theme: "Behind-the-Scenes",
    contentType: "STORY",
    title: "Study Session & Content Creation",
    description:
      "Share your study routine and content creation process in stories. Show the work behind your posts and growth journey.",
    objectives: [
      "Show authentic daily life",
      "Build personal connection",
      "Increase story engagement",
      "Drive profile visits",
    ],
    contentIdeas: [
      "Study setup and environment",
      "Content planning process",
      "Recording a reel or carousel",
      "Editing and refining content",
      "Reflection on learning",
    ],
    hashtags: ["#StudyLife", "#ContentCreator", "#BehindTheScenes"],
    estimatedTime: "20-30 minutes",
    expectedReach: "Followers + close friends",
    pointsValue: 25,
    completed: false,
    notes: "Behind-the-scenes content builds authentic connections",
  },
  {
    day: 13,
    date: "April 30, 2026",
    dayOfWeek: "Wednesday",
    week: 2,
    theme: "Community Challenge",
    contentType: "ENGAGEMENT",
    title: "Launch 7-Day Learning Challenge",
    description:
      "Create a challenge for your audience to learn something new about AI or technology for 7 days. Encourage participation and sharing.",
    objectives: [
      "Increase audience participation",
      "Build community engagement",
      "Create content series",
      "Drive user-generated content",
    ],
    contentIdeas: [
      "Define the 7-day challenge",
      "Share daily tips or resources",
      "Encourage followers to share their progress",
      "Repost user-generated content",
      "Announce winners/recognition",
    ],
    hashtags: [
      "#7DayChallenge",
      "#LearningChallenge",
      "#AIChallenge",
      "#CommunityChallenge",
    ],
    estimatedTime: "45-60 minutes",
    expectedReach: "Followers + extended network",
    pointsValue: 50,
    completed: false,
    notes: "Challenges drive 5x more engagement than regular posts",
  },
  {
    day: 14,
    date: "May 1, 2026",
    dayOfWeek: "Thursday",
    week: 2,
    theme: "Week 2 Recap & Insights",
    contentType: "CAROUSEL",
    title: "Week 2 Insights: Growth & Learnings",
    description:
      "Recap Week 2 with data insights, key learnings, and progress toward your goals. Show metrics and celebrate wins.",
    objectives: [
      "Demonstrate progress",
      "Share data and insights",
      "Build narrative momentum",
      "Inspire audience",
    ],
    contentIdeas: [
      "Slide 1: Week 2 recap title",
      "Slide 2: Engagement metrics",
      "Slide 3: Top performing post",
      "Slide 4: Key learnings",
      "Slide 5: Audience insights",
      "Slide 6: Week 3 goals",
    ],
    hashtags: [
      "#WeeklyRecap",
      "#DataInsights",
      "#GrowthMetrics",
      "#Progress",
      "#GSA2026",
    ],
    estimatedTime: "60 minutes",
    expectedReach: "1000-1400 accounts",
    pointsValue: 100,
    completed: false,
    notes: "Data-driven content shows credibility and expertise",
  },

  // WEEK 3: Engagement & Collaboration (May 2-8)
  {
    day: 15,
    date: "May 2, 2026",
    dayOfWeek: "Friday",
    week: 3,
    theme: "Collaboration Spotlight",
    contentType: "REEL",
    title: "Collab with Fellow GSA Ambassador",
    description:
      "Create a reel featuring a collaboration with another GSA ambassador. Show your partnership and combined expertise.",
    objectives: [
      "Build community relationships",
      "Cross-promote with peers",
      "Increase reach through collaboration",
      "Show community spirit",
    ],
    contentIdeas: [
      "Interview another ambassador",
      "Dual perspective on AI topic",
      "Challenge or game with peer",
      "Shared insights and tips",
      "Call-to-action to follow both",
    ],
    hashtags: [
      "#Collaboration",
      "#AmbassadorTeam",
      "#GSACommunity",
      "#TeamWork",
      "#Together",
    ],
    estimatedTime: "90-120 minutes",
    expectedReach: "1500-2200 accounts",
    pointsValue: 150,
    completed: false,
    notes: "Collaborations expand reach exponentially - both audiences see content",
  },
  {
    day: 16,
    date: "May 3, 2026",
    dayOfWeek: "Saturday",
    week: 3,
    theme: "Engagement & Interaction",
    contentType: "ENGAGEMENT",
    title: "Engage with Broader Tech Community",
    description:
      "Spend time engaging with tech creators, AI enthusiasts, and educational accounts. Build your network beyond GSA.",
    objectives: [
      "Expand network",
      "Increase visibility",
      "Learn from other creators",
      "Build cross-community relationships",
    ],
    contentIdeas: [
      "Comment on tech creator posts",
      "Share AI/tech educational content",
      "Engage with trending tech topics",
      "Follow and interact with 10+ new accounts",
    ],
    hashtags: ["#TechCommunity", "#AIEthusiasts"],
    estimatedTime: "30-45 minutes",
    expectedReach: "Network expansion",
    pointsValue: 25,
    completed: false,
    notes: "Engaging with broader community increases discoverability",
  },
  {
    day: 17,
    date: "May 4, 2026",
    dayOfWeek: "Sunday",
    week: 3,
    theme: "Practical Tips & Tricks",
    contentType: "CAROUSEL",
    title: "5 Productivity Hacks Using AI",
    description:
      "Share 5 practical productivity hacks that use AI tools to save time and improve efficiency in daily tasks.",
    objectives: [
      "Provide practical value",
      "Position as productivity expert",
      "Drive engagement and saves",
      "Build authority",
    ],
    contentIdeas: [
      "Slide 1: Eye-catching title",
      "Slides 2-6: One hack per slide",
      "Include time savings for each hack",
      "Add before/after comparisons",
      "Final slide: Challenge followers",
    ],
    hashtags: [
      "#ProductivityHacks",
      "#TimeManagement",
      "#AITools",
      "#Efficiency",
      "#LifeHacks",
    ],
    estimatedTime: "60-90 minutes",
    expectedReach: "1000-1500 accounts",
    pointsValue: 100,
    completed: false,
    notes: "How-to and hack content gets saved 3x more than other content",
  },
  {
    day: 18,
    date: "May 5, 2026",
    dayOfWeek: "Monday",
    week: 3,
    theme: "Personal Story & Vulnerability",
    contentType: "STATIC",
    title: "My Learning Journey: Failures & Growth",
    description:
      "Share a personal story about a failure or challenge in your learning journey and what you learned from it.",
    objectives: [
      "Build authentic connection",
      "Show vulnerability and humanity",
      "Inspire through struggle",
      "Build trust with audience",
    ],
    contentIdeas: [
      "A challenge you faced",
      "How you overcame it",
      "Lessons learned",
      "How it shaped you",
      "Advice for others",
    ],
    hashtags: [
      "#PersonalGrowth",
      "#LearningJourney",
      "#Vulnerability",
      "#Resilience",
      "#Growth",
    ],
    estimatedTime: "45-60 minutes",
    expectedReach: "800-1200 accounts",
    pointsValue: 75,
    completed: false,
    notes: "Vulnerable, authentic content gets highest engagement",
  },
  {
    day: 19,
    date: "May 6, 2026",
    dayOfWeek: "Tuesday",
    week: 3,
    theme: "Event Coverage",
    contentType: "STORY",
    title: "Live Event Coverage: Tech Talk or Workshop",
    description:
      "Cover a tech event, workshop, or seminar you attend. Share key takeaways and insights in stories.",
    objectives: [
      "Show real-world involvement",
      "Share valuable insights",
      "Increase story engagement",
      "Position as active community member",
    ],
    contentIdeas: [
      "Event entrance and setup",
      "Key speaker moments",
      "Audience reactions",
      "Your key takeaways",
      "Networking moments",
      "Call-to-action to attend next event",
    ],
    hashtags: ["#EventCoverage", "#TechTalk", "#Workshop", "#Learning"],
    estimatedTime: "30-45 minutes",
    expectedReach: "Followers + event attendees",
    pointsValue: 50,
    completed: false,
    notes: "Live event coverage shows real-world credibility",
  },
  {
    day: 20,
    date: "May 7, 2026",
    dayOfWeek: "Wednesday",
    week: 3,
    theme: "Q&A & Community Feedback",
    contentType: "ENGAGEMENT",
    title: "Answer Top Questions from Followers",
    description:
      "Create a carousel or reel answering the most common questions you've received from your audience.",
    objectives: [
      "Provide value to audience",
      "Address common pain points",
      "Increase engagement",
      "Build authority",
    ],
    contentIdeas: [
      "Compile top 5-7 questions",
      "Answer each one thoroughly",
      "Include visuals for each answer",
      "Encourage more questions",
      "Share in carousel or reel format",
    ],
    hashtags: [
      "#FAQ",
      "#AskMe",
      "#CommunityQuestions",
      "#Answered",
      "#Help",
    ],
    estimatedTime: "60-90 minutes",
    expectedReach: "1000-1400 accounts",
    pointsValue: 100,
    completed: false,
    notes: "FAQ content drives high engagement and positions you as expert",
  },
  {
    day: 21,
    date: "May 8, 2026",
    dayOfWeek: "Thursday",
    week: 3,
    theme: "Mid-Month Milestone",
    contentType: "CAROUSEL",
    title: "3 Weeks In: Celebrating Milestones",
    description:
      "Celebrate your 3-week progress with metrics, milestones achieved, and gratitude for your growing community.",
    objectives: [
      "Celebrate progress",
      "Show gratitude",
      "Build momentum",
      "Inspire continued engagement",
    ],
    contentIdeas: [
      "Slide 1: 3-Week milestone title",
      "Slide 2: Follower growth stats",
      "Slide 3: Engagement metrics",
      "Slide 4: Top posts and why",
      "Slide 5: Thank you to community",
      "Slide 6: What's coming next",
    ],
    hashtags: [
      "#Milestone",
      "#Grateful",
      "#Community",
      "#Growth",
      "#ThankYou",
    ],
    estimatedTime: "60 minutes",
    expectedReach: "1200-1600 accounts",
    pointsValue: 100,
    completed: false,
    notes: "Milestone posts drive high engagement and foster community loyalty",
  },

  // WEEK 4: Final Push & Optimization (May 9-15)
  {
    day: 22,
    date: "May 9, 2026",
    dayOfWeek: "Friday",
    week: 4,
    theme: "Trending Topic Deep Dive",
    contentType: "REEL",
    title: "Trending AI Topic: Deep Dive Reel",
    description:
      "Create a reel diving deep into a currently trending AI or tech topic relevant to your audience.",
    objectives: [
      "Capitalize on trending topics",
      "Increase discoverability",
      "Show timely relevance",
      "Drive engagement",
    ],
    contentIdeas: [
      "Research trending AI topic",
      "Explain it simply",
      "Show real-world applications",
      "Share your perspective",
      "Call-to-action for discussion",
    ],
    hashtags: [
      "#Trending",
      "#AINews",
      "#TechTrends",
      "#CurrentEvents",
      "#Relevant",
    ],
    estimatedTime: "60-90 minutes",
    expectedReach: "1500-2200 accounts",
    pointsValue: 125,
    completed: false,
    notes: "Trending content gets 5x more reach - timely topics are algorithm gold",
  },
  {
    day: 23,
    date: "May 10, 2026",
    dayOfWeek: "Saturday",
    week: 4,
    theme: "Community Appreciation",
    contentType: "ENGAGEMENT",
    title: "Shout-Out to Engaged Followers",
    description:
      "Recognize and thank your most engaged followers. Repost their comments, tag them, and show appreciation.",
    objectives: [
      "Build community loyalty",
      "Encourage more engagement",
      "Show you value your audience",
      "Create positive feedback loop",
    ],
    contentIdeas: [
      "Repost follower comments",
      "Tag engaged followers",
      "Share their stories",
      "Thank them publicly",
      "Encourage others to engage",
    ],
    hashtags: ["#CommunityLove", "#Grateful", "#Appreciation"],
    estimatedTime: "30-45 minutes",
    expectedReach: "Community engagement",
    pointsValue: 25,
    completed: false,
    notes: "Community appreciation increases loyalty and repeat engagement",
  },
  {
    day: 24,
    date: "May 11, 2026",
    dayOfWeek: "Sunday",
    week: 4,
    theme: "Comprehensive Guide",
    contentType: "CAROUSEL",
    title: "Complete Beginner's Guide to Google Gemini",
    description:
      "Create a comprehensive guide for beginners on how to use Google Gemini, from setup to advanced features.",
    objectives: [
      "Provide comprehensive value",
      "Establish expertise",
      "Drive high engagement",
      "Create evergreen content",
    ],
    contentIdeas: [
      "Slide 1: Guide title and overview",
      "Slide 2: What is Gemini?",
      "Slide 3: How to access it",
      "Slide 4: Basic features",
      "Slide 5: Advanced features",
      "Slide 6: Pro tips and tricks",
      "Slide 7: Common mistakes to avoid",
      "Slide 8: Call-to-action",
    ],
    hashtags: [
      "#BeginnerGuide",
      "#GoogleGemini",
      "#Tutorial",
      "#HowTo",
      "#Complete",
    ],
    estimatedTime: "90-120 minutes",
    expectedReach: "1200-1800 accounts",
    pointsValue: 150,
    completed: false,
    notes: "Comprehensive guides become evergreen content that drives long-term engagement",
  },
  {
    day: 25,
    date: "May 12, 2026",
    dayOfWeek: "Monday",
    week: 4,
    theme: "Reflection & Planning",
    contentType: "STATIC",
    title: "Month-End Reflection: What I've Learned",
    description:
      "Reflect on the entire month of content creation, growth, and learnings. Share insights about your journey.",
    objectives: [
      "Show personal growth",
      "Share valuable insights",
      "Build thought leadership",
      "Inspire your audience",
    ],
    contentIdeas: [
      "Top 5 learnings from the month",
      "Biggest challenges overcome",
      "Metrics and growth achieved",
      "What surprised you",
      "What you'd do differently",
    ],
    hashtags: [
      "#MonthlyReflection",
      "#Growth",
      "#Learnings",
      "#Gratitude",
      "#Journey",
    ],
    estimatedTime: "60 minutes",
    expectedReach: "900-1300 accounts",
    pointsValue: 100,
    completed: false,
    notes: "Reflection posts show maturity and thoughtfulness",
  },
  {
    day: 26,
    date: "May 13, 2026",
    dayOfWeek: "Tuesday",
    week: 4,
    theme: "Behind-the-Scenes Finale",
    contentType: "STORY",
    title: "One Month Journey: Before & After",
    description:
      "Share a before and after story showing your growth over the month - followers, engagement, confidence, skills.",
    objectives: [
      "Show tangible progress",
      "Inspire your audience",
      "Build confidence",
      "Celebrate achievements",
    ],
    contentIdeas: [
      "Before: First day as ambassador",
      "Journey moments throughout month",
      "After: Current status",
      "Metrics comparison",
      "Personal growth reflection",
      "Thank you to community",
    ],
    hashtags: ["#BeforeAndAfter", "#Journey", "#Growth", "#OneMonth"],
    estimatedTime: "30-45 minutes",
    expectedReach: "Followers + extended network",
    pointsValue: 50,
    completed: false,
    notes: "Before and after content is highly shareable and inspirational",
  },
  {
    day: 27,
    date: "May 14, 2026",
    dayOfWeek: "Wednesday",
    week: 4,
    theme: "Community Challenge Finale",
    contentType: "ENGAGEMENT",
    title: "Announce Challenge Winners & Celebrate",
    description:
      "Wrap up any ongoing challenges, announce winners, celebrate participation, and tease next month's challenge.",
    objectives: [
      "Close challenge loop",
      "Celebrate community",
      "Build anticipation",
      "Encourage future participation",
    ],
    contentIdeas: [
      "Announce winners",
      "Share winner stories",
      "Thank all participants",
      "Highlight best submissions",
      "Tease next month's challenge",
      "Repost user-generated content",
    ],
    hashtags: ["#ChallengeWinners", "#Celebration", "#Community", "#Grateful"],
    estimatedTime: "45-60 minutes",
    expectedReach: "Community + extended network",
    pointsValue: 75,
    completed: false,
    notes: "Challenge conclusions drive high engagement and loyalty",
  },
  {
    day: 28,
    date: "May 15, 2026",
    dayOfWeek: "Thursday",
    week: 4,
    theme: "Month Recap & Next Steps",
    contentType: "CAROUSEL",
    title: "April-May Recap: 30-Day Growth Summary",
    description:
      "Create a comprehensive recap of your entire 30-day journey with metrics, highlights, learnings, and goals for next month.",
    objectives: [
      "Celebrate full month",
      "Show comprehensive progress",
      "Share data and insights",
      "Set momentum for next month",
    ],
    contentIdeas: [
      "Slide 1: 30-Day recap title",
      "Slide 2: Follower growth stats",
      "Slide 3: Engagement metrics",
      "Slide 4: Top 3 performing posts",
      "Slide 5: Key learnings",
      "Slide 6: Community highlights",
      "Slide 7: Next month goals",
      "Slide 8: Thank you",
    ],
    hashtags: [
      "#MonthRecap",
      "#30DayJourney",
      "#GrowthSummary",
      "#Grateful",
      "#NextMonth",
    ],
    estimatedTime: "90 minutes",
    expectedReach: "1400-1800 accounts",
    pointsValue: 150,
    completed: false,
    notes: "Comprehensive recaps show professionalism and drive engagement",
  },

  // BONUS DAYS: Flexibility & Optimization (May 16-18)
  {
    day: 29,
    date: "May 16, 2026",
    dayOfWeek: "Friday",
    week: 5,
    theme: "Bonus: Trending Opportunity",
    contentType: "REEL",
    title: "Capitalize on Trending Format or Topic",
    description:
      "Use this day to create content around any trending format, sound, or topic that emerged during the month.",
    objectives: [
      "Maximize reach with trending content",
      "Stay relevant and timely",
      "Experiment with new formats",
      "Drive algorithm boost",
    ],
    contentIdeas: [
      "Trending audio reel",
      "Trending format adaptation",
      "Trending topic take",
      "Viral challenge participation",
      "Timely news commentary",
    ],
    hashtags: ["#Trending", "#FYP", "#Viral", "#Relevant"],
    estimatedTime: "45-60 minutes",
    expectedReach: "1500-2500 accounts",
    pointsValue: 125,
    completed: false,
    notes: "Trending content can go viral - always have flexibility for opportunities",
  },
  {
    day: 30,
    date: "May 17, 2026",
    dayOfWeek: "Saturday",
    week: 5,
    theme: "Bonus: Community Connection",
    contentType: "ENGAGEMENT",
    title: "Extended Q&A or Live Session",
    description:
      "Host an extended Q&A session, live stream, or deep engagement day to connect with your community.",
    objectives: [
      "Build deep community connections",
      "Answer detailed questions",
      "Show personality and expertise",
      "Drive loyalty",
    ],
    contentIdeas: [
      "Instagram Live Q&A session",
      "Extended story Q&A",
      "DM response compilation",
      "Community discussion thread",
      "Collaborative brainstorm",
    ],
    hashtags: ["#AskMe", "#Live", "#Community", "#Connect"],
    estimatedTime: "60-90 minutes",
    expectedReach: "Followers + extended network",
    pointsValue: 100,
    completed: false,
    notes: "Live engagement builds strongest community bonds",
  },
  {
    day: 31,
    date: "May 18, 2026",
    dayOfWeek: "Sunday",
    week: 5,
    theme: "Bonus: Planning & Strategy",
    contentType: "CAROUSEL",
    title: "June Planning: Next Month's Strategy",
    description:
      "Plan and share your strategy for June. Show what you learned and how you'll optimize for even better results.",
    objectives: [
      "Show strategic thinking",
      "Build anticipation for next month",
      "Demonstrate learning",
      "Inspire continued engagement",
    ],
    contentIdeas: [
      "Slide 1: June planning title",
      "Slide 2: May learnings",
      "Slide 3: What worked best",
      "Slide 4: What to improve",
      "Slide 5: June content themes",
      "Slide 6: New goals",
      "Slide 7: Collaboration plans",
      "Slide 8: Invitation to join journey",
    ],
    hashtags: [
      "#Planning",
      "#Strategy",
      "#NextMonth",
      "#Goals",
      "#Excited",
    ],
    estimatedTime: "90 minutes",
    expectedReach: "1200-1600 accounts",
    pointsValue: 150,
    completed: false,
    notes: "Forward-looking content shows professionalism and keeps audience engaged",
  },
];

// Summary Statistics
export const calendarSummary = {
  totalDays: 31,
  totalContentPieces: 31,
  contentBreakdown: {
    reels: 5,
    carousels: 10,
    staticPosts: 5,
    stories: 5,
    engagement: 6,
  },
  totalPointsAvailable: 2650,
  estimatedTotalReach: "30,000-45,000 accounts",
  estimatedTotalEngagement: "2,500-4,000 interactions",
  bestPostingDays: ["Tuesday", "Wednesday", "Thursday", "Friday"],
  bestPostingTimes: "6-9 PM IST",
  keyThemes: [
    "GSA Journey & Onboarding",
    "Educational Content",
    "Community Engagement",
    "Personal Growth",
    "Collaboration",
    "Trending Topics",
  ],
};

// Progress Tracking Helpers
export const getProgressPercentage = (completedDays: number): number => {
  return Math.round((completedDays / 31) * 100);
};

export const getPointsEarned = (completedDays: CalendarDay[]): number => {
  return completedDays.reduce((total, day) => total + (day.completed ? day.pointsValue : 0), 0);
};

export const getWeekProgress = (week: number, allDays: CalendarDay[]): number => {
  const weekDays = allDays.filter((day) => day.week === week);
  const completedWeekDays = weekDays.filter((day) => day.completed);
  return Math.round((completedWeekDays.length / weekDays.length) * 100);
};

export const getContentTypeStats = (allDays: CalendarDay[]) => {
  const stats = {
    reels: 0,
    carousels: 0,
    staticPosts: 0,
    stories: 0,
    engagement: 0,
  };

  allDays.forEach((day) => {
    if (day.contentType === "REEL") stats.reels++;
    else if (day.contentType === "CAROUSEL") stats.carousels++;
    else if (day.contentType === "STATIC") stats.staticPosts++;
    else if (day.contentType === "STORY") stats.stories++;
    else if (day.contentType === "ENGAGEMENT") stats.engagement++;
  });

  return stats;
};
