// Simplified 30-Day Content Calendar - Starting May 13, 2026 (Today)
// Updated dates for current month

export interface SimpleDayTask {
  day: number;
  date: string;
  dayOfWeek: string;
  contentType: "REEL" | "CAROUSEL" | "POST" | "STORY" | "ENGAGEMENT";
  title: string;
  description: string;
  ideas: string[];
  hashtags: string[];
  timeNeeded: string;
  pointsValue: number;
  completed: boolean;
}

export const simplifiedCalendar: SimpleDayTask[] = [
  // WEEK 1: May 13-19, 2026
  {
    day: 1,
    date: "May 13, 2026",
    dayOfWeek: "Tuesday",
    contentType: "REEL",
    title: "GSA Journey Kickoff 🚀",
    description: "Launch your GSA ambassador journey with an energetic reel",
    ideas: [
      "Quick clips from GSA onboarding",
      "Your reaction to becoming ambassador",
      "Campus highlights",
      "Why you joined GSA",
    ],
    hashtags: ["#GSA2026", "#GoogleStudentAmbassador", "#TeamGemini"],
    timeNeeded: "60 min",
    pointsValue: 100,
    completed: true,
  },
  {
    day: 2,
    date: "May 14, 2026",
    dayOfWeek: "Wednesday",
    contentType: "ENGAGEMENT",
    title: "Engage with GSA Community",
    description: "Interact with other ambassador posts and build community",
    ideas: [
      "Comment on 5-10 GSA posts",
      "Share insights in comments",
      "Reply to your post comments",
      "DM 2-3 ambassadors",
    ],
    hashtags: ["#GSACommunity", "#AmbassadorNetwork"],
    timeNeeded: "30 min",
    pointsValue: 25,
    completed: false,
  },
  {
    day: 3,
    date: "May 15, 2026",
    dayOfWeek: "Thursday",
    contentType: "CAROUSEL",
    title: "5 Must-Have AI Tools for Students",
    description: "Educational carousel with practical AI tools and use cases",
    ideas: [
      "ChatGPT for writing",
      "Gemini for research",
      "Copilot for coding",
      "Midjourney for design",
      "Grammarly for editing",
    ],
    hashtags: ["#AITools", "#StudentTech", "#Productivity"],
    timeNeeded: "90 min",
    pointsValue: 100,
    completed: false,
  },
  {
    day: 4,
    date: "May 16, 2026",
    dayOfWeek: "Friday",
    contentType: "POST",
    title: "Motivational Quote & Reflection",
    description: "Share an inspiring message about growth and learning",
    ideas: [
      "Quote about learning",
      "Your personal story",
      "Call-to-action for followers",
      "Beautiful design",
    ],
    hashtags: ["#Motivation", "#Growth", "#StudentLife"],
    timeNeeded: "45 min",
    pointsValue: 50,
    completed: false,
  },
  {
    day: 5,
    date: "May 17, 2026",
    dayOfWeek: "Saturday",
    contentType: "STORY",
    title: "Day in Life as GSA Ambassador",
    description: "Share authentic daily moments in your stories",
    ideas: [
      "Morning routine",
      "Study session",
      "Working on GSA tasks",
      "Evening reflection",
    ],
    hashtags: ["#DayInMyLife", "#BehindTheScenes"],
    timeNeeded: "30 min",
    pointsValue: 25,
    completed: false,
  },
  {
    day: 6,
    date: "May 18, 2026",
    dayOfWeek: "Sunday",
    contentType: "ENGAGEMENT",
    title: "Host Q&A in Stories",
    description: "Ask your audience questions and engage with responses",
    ideas: [
      "Poll: What's your biggest tech challenge?",
      "Question: What AI tool do you want to learn?",
      "Poll: Reel or Carousel preference?",
      "Share responses in next post",
    ],
    hashtags: ["#AskMe", "#Community"],
    timeNeeded: "20 min",
    pointsValue: 25,
    completed: false,
  },
  {
    day: 7,
    date: "May 19, 2026",
    dayOfWeek: "Monday",
    contentType: "CAROUSEL",
    title: "Week 1 Recap: What I Learned",
    description: "Reflect on your week and share key learnings",
    ideas: [
      "3 key learnings",
      "Challenges overcome",
      "Metrics from the week",
      "Goals for Week 2",
    ],
    hashtags: ["#WeeklyRecap", "#GrowthJourney", "#Reflection"],
    timeNeeded: "60 min",
    pointsValue: 100,
    completed: false,
  },

  // WEEK 2: May 20-26, 2026
  {
    day: 8,
    date: "May 20, 2026",
    dayOfWeek: "Tuesday",
    contentType: "REEL",
    title: "Google Gemini Tutorial",
    description: "Quick tutorial on how to use Google Gemini",
    ideas: [
      "Screen recording of Gemini",
      "Step-by-step walkthrough",
      "3 practical use cases",
      "Tips and tricks",
    ],
    hashtags: ["#GoogleGemini", "#Tutorial", "#HowTo"],
    timeNeeded: "90 min",
    pointsValue: 100,
    completed: false,
  },
  {
    day: 9,
    date: "May 21, 2026",
    dayOfWeek: "Wednesday",
    contentType: "ENGAGEMENT",
    title: "Respond to All Comments",
    description: "Engage deeply with your community",
    ideas: [
      "Reply to all comments thoughtfully",
      "Answer DM questions",
      "Create a post from questions",
      "Thank people for engagement",
    ],
    hashtags: ["#CommunityFirst"],
    timeNeeded: "45 min",
    pointsValue: 25,
    completed: false,
  },
  {
    day: 10,
    date: "May 22, 2026",
    dayOfWeek: "Thursday",
    contentType: "CAROUSEL",
    title: "Student Success Story",
    description: "Share how AI changed someone's learning",
    ideas: [
      "The challenge",
      "The AI solution",
      "Results and impact",
      "Key takeaways",
    ],
    hashtags: ["#SuccessStory", "#AIInEducation", "#Learning"],
    timeNeeded: "90 min",
    pointsValue: 100,
    completed: false,
  },
  {
    day: 11,
    date: "May 23, 2026",
    dayOfWeek: "Friday",
    contentType: "POST",
    title: "Friday Motivation",
    description: "End the week strong with motivational content",
    ideas: [
      "Weekly achievement",
      "Motivational message",
      "Weekend challenge",
      "Inspiring visual",
    ],
    hashtags: ["#FridayFeeling", "#Motivation", "#WeekendReady"],
    timeNeeded: "45 min",
    pointsValue: 50,
    completed: false,
  },
  {
    day: 12,
    date: "May 24, 2026",
    dayOfWeek: "Saturday",
    contentType: "STORY",
    title: "Study & Content Creation",
    description: "Show your study routine and content process",
    ideas: [
      "Study setup",
      "Content planning",
      "Recording process",
      "Editing workflow",
    ],
    hashtags: ["#StudyLife", "#ContentCreator"],
    timeNeeded: "30 min",
    pointsValue: 25,
    completed: false,
  },
  {
    day: 13,
    date: "May 25, 2026",
    dayOfWeek: "Sunday",
    contentType: "ENGAGEMENT",
    title: "Launch 7-Day Challenge",
    description: "Create a challenge for your audience",
    ideas: [
      "Define the challenge",
      "Share daily tips",
      "Encourage participation",
      "Repost user content",
    ],
    hashtags: ["#7DayChallenge", "#LearningChallenge"],
    timeNeeded: "60 min",
    pointsValue: 50,
    completed: false,
  },
  {
    day: 14,
    date: "May 26, 2026",
    dayOfWeek: "Monday",
    contentType: "CAROUSEL",
    title: "Week 2 Insights & Data",
    description: "Share metrics and growth insights",
    ideas: [
      "Engagement metrics",
      "Top performing post",
      "Audience insights",
      "Week 3 goals",
    ],
    hashtags: ["#DataInsights", "#Growth", "#Progress"],
    timeNeeded: "60 min",
    pointsValue: 100,
    completed: false,
  },

  // WEEK 3: May 27 - June 2, 2026
  {
    day: 15,
    date: "May 27, 2026",
    dayOfWeek: "Tuesday",
    contentType: "REEL",
    title: "Collab with Fellow Ambassador",
    description: "Create content with another GSA ambassador",
    ideas: [
      "Interview another ambassador",
      "Dual perspective on AI",
      "Challenge with peer",
      "Shared insights",
    ],
    hashtags: ["#Collaboration", "#AmbassadorTeam", "#Together"],
    timeNeeded: "120 min",
    pointsValue: 150,
    completed: false,
  },
  {
    day: 16,
    date: "May 28, 2026",
    dayOfWeek: "Wednesday",
    contentType: "ENGAGEMENT",
    title: "Engage with Tech Community",
    description: "Build your network beyond GSA",
    ideas: [
      "Comment on tech posts",
      "Share educational content",
      "Follow new accounts",
      "Join conversations",
    ],
    hashtags: ["#TechCommunity", "#Networking"],
    timeNeeded: "45 min",
    pointsValue: 25,
    completed: false,
  },
  {
    day: 17,
    date: "May 29, 2026",
    dayOfWeek: "Thursday",
    contentType: "CAROUSEL",
    title: "5 Productivity Hacks",
    description: "Share practical AI productivity tips",
    ideas: [
      "Time-saving hack 1",
      "Time-saving hack 2",
      "Time-saving hack 3",
      "Time-saving hack 4",
      "Time-saving hack 5",
    ],
    hashtags: ["#ProductivityHacks", "#TimeManagement", "#LifeHacks"],
    timeNeeded: "90 min",
    pointsValue: 100,
    completed: false,
  },
  {
    day: 18,
    date: "May 30, 2026",
    dayOfWeek: "Friday",
    contentType: "POST",
    title: "Personal Story: Failures & Growth",
    description: "Share a challenge you overcame",
    ideas: [
      "A challenge you faced",
      "How you overcame it",
      "Lessons learned",
      "Advice for others",
    ],
    hashtags: ["#PersonalGrowth", "#Resilience", "#Learning"],
    timeNeeded: "60 min",
    pointsValue: 75,
    completed: false,
  },
  {
    day: 19,
    date: "May 31, 2026",
    dayOfWeek: "Saturday",
    contentType: "STORY",
    title: "Event Coverage",
    description: "Cover a tech event or workshop",
    ideas: [
      "Event entrance",
      "Key moments",
      "Audience reactions",
      "Your takeaways",
    ],
    hashtags: ["#EventCoverage", "#TechTalk"],
    timeNeeded: "45 min",
    pointsValue: 50,
    completed: false,
  },
  {
    day: 20,
    date: "June 1, 2026",
    dayOfWeek: "Sunday",
    contentType: "ENGAGEMENT",
    title: "Answer Top Questions",
    description: "Create content answering common questions",
    ideas: [
      "Compile top questions",
      "Answer each one",
      "Add visuals",
      "Encourage more questions",
    ],
    hashtags: ["#FAQ", "#AskMe", "#Answered"],
    timeNeeded: "90 min",
    pointsValue: 100,
    completed: false,
  },
  {
    day: 21,
    date: "June 2, 2026",
    dayOfWeek: "Monday",
    contentType: "CAROUSEL",
    title: "3 Weeks In: Celebrating Milestones",
    description: "Celebrate your progress and thank community",
    ideas: [
      "Follower growth stats",
      "Engagement metrics",
      "Top posts",
      "Thank you message",
    ],
    hashtags: ["#Milestone", "#Grateful", "#Community"],
    timeNeeded: "60 min",
    pointsValue: 100,
    completed: false,
  },

  // WEEK 4: June 3-9, 2026
  {
    day: 22,
    date: "June 3, 2026",
    dayOfWeek: "Tuesday",
    contentType: "REEL",
    title: "Trending AI Topic Deep Dive",
    description: "Create a reel on a currently trending topic",
    ideas: [
      "Research trending topic",
      "Explain simply",
      "Real-world applications",
      "Your perspective",
    ],
    hashtags: ["#Trending", "#AINews", "#TechTrends"],
    timeNeeded: "90 min",
    pointsValue: 125,
    completed: false,
  },
  {
    day: 23,
    date: "June 4, 2026",
    dayOfWeek: "Wednesday",
    contentType: "ENGAGEMENT",
    title: "Shout-Out to Engaged Followers",
    description: "Recognize and thank your most engaged followers",
    ideas: [
      "Repost follower comments",
      "Tag engaged followers",
      "Share their stories",
      "Thank them publicly",
    ],
    hashtags: ["#CommunityLove", "#Grateful"],
    timeNeeded: "45 min",
    pointsValue: 25,
    completed: false,
  },
  {
    day: 24,
    date: "June 5, 2026",
    dayOfWeek: "Thursday",
    contentType: "CAROUSEL",
    title: "Complete Gemini Beginner's Guide",
    description: "Comprehensive guide to using Google Gemini",
    ideas: [
      "What is Gemini?",
      "How to access it",
      "Basic features",
      "Advanced features",
      "Pro tips",
      "Common mistakes",
    ],
    hashtags: ["#BeginnerGuide", "#GoogleGemini", "#Tutorial"],
    timeNeeded: "120 min",
    pointsValue: 150,
    completed: false,
  },
  {
    day: 25,
    date: "June 6, 2026",
    dayOfWeek: "Friday",
    contentType: "POST",
    title: "Month-End Reflection",
    description: "Reflect on your journey and learnings",
    ideas: [
      "Top 5 learnings",
      "Biggest challenges",
      "Metrics achieved",
      "What surprised you",
    ],
    hashtags: ["#Reflection", "#Growth", "#Gratitude"],
    timeNeeded: "60 min",
    pointsValue: 100,
    completed: false,
  },
  {
    day: 26,
    date: "June 7, 2026",
    dayOfWeek: "Saturday",
    contentType: "STORY",
    title: "One Month Journey: Before & After",
    description: "Show your growth over the month",
    ideas: [
      "First day as ambassador",
      "Journey moments",
      "Current status",
      "Metrics comparison",
      "Thank you to community",
    ],
    hashtags: ["#BeforeAndAfter", "#Journey", "#Growth"],
    timeNeeded: "45 min",
    pointsValue: 50,
    completed: false,
  },
  {
    day: 27,
    date: "June 8, 2026",
    dayOfWeek: "Sunday",
    contentType: "ENGAGEMENT",
    title: "Announce Challenge Winners",
    description: "Wrap up challenges and celebrate community",
    ideas: [
      "Announce winners",
      "Share winner stories",
      "Thank participants",
      "Tease next challenge",
    ],
    hashtags: ["#ChallengeWinners", "#Celebration"],
    timeNeeded: "60 min",
    pointsValue: 75,
    completed: false,
  },
  {
    day: 28,
    date: "June 9, 2026",
    dayOfWeek: "Monday",
    contentType: "CAROUSEL",
    title: "30-Day Growth Summary",
    description: "Comprehensive recap of your entire month",
    ideas: [
      "Follower growth stats",
      "Engagement metrics",
      "Top 3 posts",
      "Key learnings",
      "Next month goals",
    ],
    hashtags: ["#MonthRecap", "#GrowthSummary", "#Grateful"],
    timeNeeded: "90 min",
    pointsValue: 150,
    completed: false,
  },

  // BONUS DAYS: Flexibility
  {
    day: 29,
    date: "June 10, 2026",
    dayOfWeek: "Tuesday",
    contentType: "REEL",
    title: "Capitalize on Trending Format",
    description: "Create content around any trending format",
    ideas: [
      "Trending audio reel",
      "Trending format",
      "Trending topic",
      "Viral challenge",
    ],
    hashtags: ["#Trending", "#FYP", "#Viral"],
    timeNeeded: "60 min",
    pointsValue: 125,
    completed: false,
  },
  {
    day: 30,
    date: "June 11, 2026",
    dayOfWeek: "Wednesday",
    contentType: "ENGAGEMENT",
    title: "Extended Q&A or Live Session",
    description: "Deep engagement with your community",
    ideas: [
      "Instagram Live Q&A",
      "Story Q&A",
      "DM response compilation",
      "Community discussion",
    ],
    hashtags: ["#AskMe", "#Live", "#Community"],
    timeNeeded: "90 min",
    pointsValue: 100,
    completed: false,
  },
];

// Summary stats
export const calendarStats = {
  totalDays: 30,
  totalPoints: 2500,
  contentBreakdown: {
    reels: 5,
    carousels: 8,
    posts: 5,
    stories: 5,
    engagement: 7,
  },
  bestDays: ["Tuesday", "Wednesday", "Thursday", "Friday"],
  bestTime: "6-9 PM IST",
};

export const getTodayTask = (): SimpleDayTask | null => {
  const today = new Date();
  const todayString = today.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  return simplifiedCalendar.find((day) => day.date === todayString) || null;
};

export const getUpcomingTasks = (days: number = 7): SimpleDayTask[] => {
  const today = new Date();
  return simplifiedCalendar.filter((day) => {
    const taskDate = new Date(day.date);
    const daysFromNow = Math.floor(
      (taskDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24)
    );
    return daysFromNow >= 0 && daysFromNow <= days;
  });
};

export const getProgressPercentage = (completedDays: number): number => {
  return Math.round((completedDays / 30) * 100);
};
